### ISSUE TITLE
Color picker in preferences.

### ISSUE THREAD

**Issue by ravecode** [Qusic/Couria#24]
A color picker (such as [libColorPicker](https://bitbucket.org/pixelfiredev/libcolorpicker/) or [NKOColorPickerView](https://github.com/FWCarlos/NKO-Color-Picker-View-iOS)) should be integrated into the preferences panel for the user to easily and effectively select their desired color choices.

**Comment by Terry174** [comment]
I've actually ported RKColorPicker to a references specifier. I plan to release a library alongside some tweak updates I have nearly completed. It offers a native preference saving mechanism, unlike the alternatives which write directly to property lists, I believe this has an advantage since it can be easily overridden or you can choose to stick with CFPreferences if you wish. In any case I'll release headers alongside this library and hopefully some people will find it useful.
